### ISSUE TITLE
[SDKs] C Client

### ISSUE THREAD

**Issue by grudich** [dojoengine/dojo.c#14]
```[tasklist]
### Tasks
- [ ] https://github.com/dojoengine/dojo.c/pull/16
- [ ] https://github.com/dojoengine/dojo.c/pull/13
- [x] Wasm support
- [ ] Tests across entire bindings
- [ ] Android and iOS builds
```
